"""Initial migration

Revision ID: ae31e5fce1c2
Revises: 
Create Date: 2025-12-11 10:25:00.107890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae31e5fce1c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('current_prescription_od_sph', sa.Float(), nullable=True),
    sa.Column('current_prescription_od_cyl', sa.Float(), nullable=True),
    sa.Column('current_prescription_od_axis', sa.Integer(), nullable=True),
    sa.Column('current_prescription_os_sph', sa.Float(), nullable=True),
    sa.Column('current_prescription_os_cyl', sa.Float(), nullable=True),
    sa.Column('current_prescription_os_axis', sa.Integer(), nullable=True),
    sa.Column('lens_type', sa.String(length=50), nullable=True),
    sa.Column('lens_brand', sa.String(length=100), nullable=True),
    sa.Column('lens_purchase_date', sa.Date(), nullable=True),
    sa.Column('avg_screen_time_hours', sa.Float(), nullable=True),
    sa.Column('avg_sleep_hours', sa.Float(), nullable=True),
    sa.Column('lighting_condition', sa.String(length=50), nullable=True),
    sa.Column('activity_level', sa.String(length=50), nullable=True),
    sa.Column('data_storage_preference', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('alert_data', sa.JSON(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('is_dismissed', sa.Boolean(), nullable=True),
    sa.Column('is_actionable', sa.Boolean(), nullable=True),
    sa.Column('action_taken', sa.Boolean(), nullable=True),
    sa.Column('action_taken_at', sa.DateTime(), nullable=True),
    sa.Column('push_sent', sa.Boolean(), nullable=True),
    sa.Column('email_sent', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_user_id'), ['user_id'], unique=False)

    op.create_table('lens_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lens_type', sa.String(length=50), nullable=False),
    sa.Column('lens_brand', sa.String(length=100), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('prescription_od_sph', sa.Float(), nullable=True),
    sa.Column('prescription_od_cyl', sa.Float(), nullable=True),
    sa.Column('prescription_od_axis', sa.Integer(), nullable=True),
    sa.Column('prescription_os_sph', sa.Float(), nullable=True),
    sa.Column('prescription_os_cyl', sa.Float(), nullable=True),
    sa.Column('prescription_os_axis', sa.Integer(), nullable=True),
    sa.Column('effectiveness_score', sa.Float(), nullable=True),
    sa.Column('vision_clarity_score', sa.Float(), nullable=True),
    sa.Column('baseline_vision_score', sa.Float(), nullable=True),
    sa.Column('current_vision_score', sa.Float(), nullable=True),
    sa.Column('effectiveness_decline_rate', sa.Float(), nullable=True),
    sa.Column('predicted_replacement_date', sa.Date(), nullable=True),
    sa.Column('replacement_recommended', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('replaced_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lens_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lens_data_user_id'), ['user_id'], unique=False)

    op.create_table('lifestyle_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('screen_time_hours', sa.Float(), nullable=True),
    sa.Column('screen_time_breakdown', sa.JSON(), nullable=True),
    sa.Column('sleep_hours', sa.Float(), nullable=True),
    sa.Column('sleep_quality', sa.Integer(), nullable=True),
    sa.Column('lighting_condition', sa.String(length=50), nullable=True),
    sa.Column('blue_light_exposure_hours', sa.Float(), nullable=True),
    sa.Column('activity_level', sa.String(length=50), nullable=True),
    sa.Column('outdoor_time_hours', sa.Float(), nullable=True),
    sa.Column('exercise_minutes', sa.Integer(), nullable=True),
    sa.Column('breaks_taken', sa.Integer(), nullable=True),
    sa.Column('eye_drops_used', sa.Boolean(), nullable=True),
    sa.Column('eye_strain_level', sa.Integer(), nullable=True),
    sa.Column('headache_level', sa.Integer(), nullable=True),
    sa.Column('dry_eyes', sa.Boolean(), nullable=True),
    sa.Column('blurred_vision', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lifestyle_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lifestyle_logs_log_date'), ['log_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_lifestyle_logs_user_id'), ['user_id'], unique=False)

    op.create_table('vision_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('test_type', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('errors', sa.Integer(), nullable=True),
    sa.Column('test_details', sa.JSON(), nullable=True),
    sa.Column('left_eye_score', sa.Float(), nullable=True),
    sa.Column('right_eye_score', sa.Float(), nullable=True),
    sa.Column('lighting_condition', sa.String(length=50), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vision_tests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vision_tests_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_vision_tests_user_id'), ['user_id'], unique=False)

    op.create_table('vision_trends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('period_type', sa.String(length=20), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('avg_vision_score', sa.Float(), nullable=True),
    sa.Column('avg_acuity_score', sa.Float(), nullable=True),
    sa.Column('avg_contrast_score', sa.Float(), nullable=True),
    sa.Column('avg_color_score', sa.Float(), nullable=True),
    sa.Column('vision_score_change', sa.Float(), nullable=True),
    sa.Column('avg_fatigue_score', sa.Float(), nullable=True),
    sa.Column('avg_blink_rate', sa.Float(), nullable=True),
    sa.Column('avg_redness_level', sa.Float(), nullable=True),
    sa.Column('fatigue_score_change', sa.Float(), nullable=True),
    sa.Column('avg_lens_effectiveness', sa.Float(), nullable=True),
    sa.Column('lens_effectiveness_change', sa.Float(), nullable=True),
    sa.Column('avg_screen_time', sa.Float(), nullable=True),
    sa.Column('avg_sleep_hours', sa.Float(), nullable=True),
    sa.Column('predicted_vision_change_30d', sa.Float(), nullable=True),
    sa.Column('predicted_prescription_change', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vision_trends', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vision_trends_period_start'), ['period_start'], unique=False)
        batch_op.create_index(batch_op.f('ix_vision_trends_user_id'), ['user_id'], unique=False)

    op.create_table('webcam_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('blink_rate', sa.Float(), nullable=True),
    sa.Column('incomplete_blinks', sa.Integer(), nullable=True),
    sa.Column('avg_blink_duration_ms', sa.Float(), nullable=True),
    sa.Column('squint_count', sa.Integer(), nullable=True),
    sa.Column('squint_duration_seconds', sa.Float(), nullable=True),
    sa.Column('sclera_redness_level', sa.Float(), nullable=True),
    sa.Column('tear_film_quality', sa.Float(), nullable=True),
    sa.Column('pupil_size_variation', sa.Float(), nullable=True),
    sa.Column('fatigue_score', sa.Float(), nullable=False),
    sa.Column('session_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('analysis_frames', sa.Integer(), nullable=True),
    sa.Column('video_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webcam_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webcam_metrics_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_webcam_metrics_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webcam_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webcam_metrics_user_id'))
        batch_op.drop_index(batch_op.f('ix_webcam_metrics_created_at'))

    op.drop_table('webcam_metrics')
    with op.batch_alter_table('vision_trends', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vision_trends_user_id'))
        batch_op.drop_index(batch_op.f('ix_vision_trends_period_start'))

    op.drop_table('vision_trends')
    with op.batch_alter_table('vision_tests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vision_tests_user_id'))
        batch_op.drop_index(batch_op.f('ix_vision_tests_created_at'))

    op.drop_table('vision_tests')
    with op.batch_alter_table('lifestyle_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lifestyle_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_lifestyle_logs_log_date'))

    op.drop_table('lifestyle_logs')
    with op.batch_alter_table('lens_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lens_data_user_id'))

    op.drop_table('lens_data')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_user_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_created_at'))

    op.drop_table('alerts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
