"""Add blink calibration threshold to User model

Revision ID: b439affe4c60
Revises: ae31e5fce1c2
Create Date: 2025-12-14 16:29:39.705873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b439affe4c60'
down_revision = 'ae31e5fce1c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blink_threshold', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('blink_threshold_updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('blink_threshold_updated_at')
        batch_op.drop_column('blink_threshold')

    # ### end Alembic commands ###
